name: Minimal Project Check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check critical files
        run: |
          if [ ! -f .gitignore ]; then echo "Warning: .gitignore is missing"; fi
